steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myfirstimage:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/myfirstimage"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'gcdc-nd', '--image', 'gcr.io/$PROJECT_ID/myfirstimage:${SHORT_SHA}', '--region', 'us-central1']
